### ISSUE TITLE
README Broken link

### ISSUE THREAD

**Issue by marcalmp** [STMicroelectronics/stm32h7s78-dk-bsp#1]
README.md
https://github.com/STMicroelectronics/stm32-aps256xx ->
https://github.com/STMicroelectronics/stm32-aps256

**Comment by ALABSTM** [comment]
Hi @marcalmp,

Thank you for the heads-up. We'll have this fixed soon enough hopefully.

With regards,

**Comment by KRASTM** [comment]
Fixed in commit: https://github.com/STMicroelectronics/stm32h7s78-dk-bsp/commit/0dc1925f399439396aac825de83fbbd305202dc5
